apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/adminsys2023-intranet: "true"
        io.kompose.service: frontend
    spec:
      containers:
        - env:
            - name: APP_BACKEND_HOST
              value: backend
            - name: APP_BACKEND_PORT
              value: "3000"
            - name: NODE_ENV
              value: development
          image: app-frontend
          name: frontend
          ports:
            - containerPort: 80
              hostPort: 8080
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
